services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./client
    env_file:
      - .env
    depends_on:
      - rabbitmq

  worker-add:
    build: ./worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: ["node", "worker.js", "add"]

  worker-sub:
    build: ./worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: ["node", "worker.js", "sub"]

  worker-mul:
    build: ./worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: ["node", "worker.js", "mul"]

  worker-div:
    build: ./worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: ["node", "worker.js", "div"]

  consumer:
    build: ./consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq