version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq # persiste les messages & conf
    restart: unless-stopped # redémarre au boot
    healthcheck: # optionnel : statut santé
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq-data:
